version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets: 
    - db_root_password
    - db_password
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    secrets: 
    - db_password
    - credentials
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ayse/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ayse/data/mariadb

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  